# Generated by Django 4.2.2 on 2023-06-16 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(default='static/ecommerce/images/index.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=10)),
                ('sexe', models.CharField(max_length=10)),
                ('x', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('y', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('image', models.ImageField(default='static/ecommerce/images/index.png', null=True, upload_to='')),
                ('description', models.TextField(default='', editable=False, max_length=400)),
                ('adresse', models.CharField(default='', editable=False, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modePaiment', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ecommerce.client')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('status', models.CharField(max_length=20)),
                ('nom_boutique', models.CharField(max_length=100)),
                ('x', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('y', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarquePrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.IntegerField(default=1, max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='ecommerce/static/ecommerce/images')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categorie')),
                ('fournisseurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.fournisseur')),
                ('marqueprives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.marqueprive')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl', to='ecommerce.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='ecommerce.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='ecommerce.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='ecommerce.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modePaiment', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=100)),
                ('prixtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ok', models.CharField(max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cli', to='ecommerce.client')),
            ],
        ),
        migrations.CreateModel(
            name='Commandeitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('etat', models.CharField(default='first', max_length=50)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='ecommerce.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ecommerce.produit')),
            ],
            options={
                'verbose_name': 'Commandeitem',
                'verbose_name_plural': 'Commandeitem',
            },
        ),
    ]
