# Generated by Django 4.0.6 on 2022-07-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nni', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=50)),
            ],
        ),
    ]
