# Generated by Django 4.0.6 on 2022-08-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_commande_commandeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(default='static/ecommerce/images/index.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default='static/ecommerce/images/index.png', upload_to=''),
        ),
    ]
