# Generated by Django 4.1 on 2022-08-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_categorie_image_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(default='static/ecommerce/images/index.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='static/ecommerce/images/index.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
