# Generated by Django 4.1 on 2022-08-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_client_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='fournisseurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.fournisseur'),
        ),
    ]
