# Generated by Django 4.0.6 on 2022-07-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_categorie_marqueprive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
