# Generated by Django 4.1 on 2022-08-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_produit_fournisseurs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'verbose_name': 'Fournisseur'},
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, default='', editable=False, max_length=400),
        ),
        migrations.AlterField(
            model_name='client',
            name='sexe',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
