# Generated by Django 4.0.6 on 2022-07-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
