# Generated by Django 4.1 on 2022-08-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_demande'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demande',
        ),
    ]
