# Generated by Django 4.0.6 on 2022-07-29 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_delete_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.service')),
            ],
        ),
    ]
