# Generated by Django 4.0.6 on 2022-07-29 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=7, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('fournisseurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.fournisseur')),
                ('marqueprives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.marqueprive')),
            ],
        ),
    ]
