# Generated by Django 4.1 on 2022-08-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_delete_demande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modePaiment', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=100)),
                ('prixtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cli', to='ecommerce.client')),
                ('paniers', models.ManyToManyField(blank=True, related_name='panie', to='ecommerce.panier')),
            ],
        ),
    ]
