# Generated by Django 4.1 on 2022-08-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_demande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='paniers',
        ),
    ]
