# Generated by Django 4.0.6 on 2022-09-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_demande_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(default='Mauritania - nouakchott', max_length=100),
        ),
    ]
