# Generated by Django 4.0.6 on 2022-09-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_fournisseur_adresse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandeitem',
            options={'verbose_name': 'Commandeitem', 'verbose_name_plural': 'Commandeitem'},
        ),
    ]
