# Generated by Django 4.0.6 on 2022-09-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_commandeitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='adresse',
        ),
        migrations.AddField(
            model_name='client',
            name='x',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='client',
            name='y',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='commandeitem',
            name='etat',
            field=models.CharField(default='first', max_length=50),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='x',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='y',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
